baseURL = 'https://github.keitaw.io'
languageCode = 'en-us'
title = 'Keita Watanabe'
theme = 'PaperMod'
[caches]
  [caches.images]
    dir = ':cacheDir/images'
[params.assets]
  favicon = "favicon.svg"
  favicon16x16 = "favicon.svg"
  favicon32x32 = "favicon.svg"
[[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/"
    weight = 1
[[menu.main]]
    identifier = "about"
    name = "About me"
    url = "/about"
    weight = 2

[[params.socialIcons]]
    name = "Github"
    url = "https://github.com/KeitaW"
[[params.socialIcons]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/keitawatanabe/"