baseURL = 'https://github.keitaw.io'
languageCode = 'en-us'
title = 'Keita Watanabe'
theme = 'PaperMod'
[caches]
  [caches.images]
    dir = ':cacheDir/images'
[params]
  [params.assets]
    favicon = "/favicon.ico"