baseURL = 'https://github.keitaw.io'
languageCode = 'en-us'
title = 'Keita Watanabe'
theme = 'PaperMod'
[caches]
  [caches.images]
    dir = ':cacheDir/images'
[params.assets]
  favicon = "favicon.svg"
  favicon16x16 = "favicon.svg"
  favicon32x32 = "favicon.svg"